/*
5) Add the number of total purchases to query 4.
*/

SELECT
    CONCAT(CUSTOMER.CUS_FNAME, ' ', CUSTOMER.CUS_LNAME) AS `Customer Name`,
    CUSTOMER.CUS_BALANCE AS `Customer Balance`,
    SUM(LINE.LINE_UNITS * LINE.LINE_PRICE) AS `Total Purchases`,
    COUNT(INVOICE.INV_NUMBER) AS `Number of Purchases`
FROM CUSTOMER
LEFT JOIN INVOICE ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE
LEFT JOIN LINE ON INVOICE.INV_NUMBER = LINE.INV_NUMBER
GROUP BY `Customer Name`, `Customer Balance`;
