SELECT CONCAT(AUTHOR.AU_FNAME, ' ', AUTHOR.AU_LNAME) AS AUTHOR_NAME,
	   BOOK_TITLE, BOOK_SUBJECT
FROM AUTHOR
JOIN WRITES ON AUTHOR.AU_ID = WRITES.AU_ID
JOIN BOOK ON WRITES.BOOK_NUM = BOOK.BOOK_NUM
ORDER BY BOOK_SUBJECT;