EXPLAIN SELECT *
FROM PRODUCT P
INNER JOIN LINE L ON P.P_CODE = L.P_CODE
INNER JOIN INVOICE I ON L.INV_NUMBER = I.INV_NUMBER
INNER JOIN CUSTOMER C ON I.CUS_CODE = C.CUS_CODE
WHERE C.CUS_BALANCE > 500
AND P.P_PRICE > 50
ORDER BY I.INV_NUMBER;
