EXPLAIN SELECT *
FROM INVOICE I
INNER JOIN CUSTOMER C ON I.CUS_CODE = C.CUS_CODE
INNER JOIN LINE L ON I.INV_NUMBER = L.INV_NUMBER
INNER JOIN PRODUCT P ON L.P_CODE = P.P_CODE
WHERE C.CUS_BALANCE > 500
AND P.P_PRICE > 50
ORDER BY I.INV_NUMBER;