EXPLAIN SELECT MAX_UNITS_TABLE.P_CODE, SUM(LINE_UNITS)
FROM LINE
JOIN (
  SELECT P_CODE, MAX(LINE_UNITS) AS MAX_UNITS
  FROM LINE
  GROUP BY P_CODE
) AS MAX_UNITS_TABLE ON LINE.P_CODE = MAX_UNITS_TABLE.P_CODE
GROUP BY MAX_UNITS_TABLE.P_CODE
HAVING SUM(LINE_UNITS) > MAX(MAX_UNITS_TABLE.MAX_UNITS);